name: AWS 테라폼으로 배포


on:
  workflow_dispatch:
    inputs:
      provision_aws:
        description: "AWS 인프라 리소스를 만드시겠습니까? (네/아니요)"
        required: true
        default: '네'
        
defaults:
  run:
    working-directory: devops/infra/aws
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Terraform-Script:
    runs-on: ubuntu-latest
    name: 테라폼 실행
    if: ${{ github.event.inputs.provision_aws == '네' }}

    steps:
      - name: 파일 체크아웃
        uses: actions/checkout@v2

      - name: 테라폼 셋업
        uses: hashicorp/setup-terraform@v1

      - name: 테라폼 설정
        id: init
        run: terraform init

      - name: 테라폼 확인
        id: validate
        run: terraform validate -no-color

      - name: 테라폼 계획
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
 
      - name: 테라폼 적용
        id: apply
        run: terraform apply -auto-approve
